# Version of the config.yml
version: "v2.0.0"

# Name of the challenge
name: "Cracking password"

# Challenge difficulty: 10 - 500
difficulty: 50

# Enable inputbox to submit flag: true | false
enable_flag_input: true

# If the solution is a fix string (static flag) you can add it here
flag: '9)":&4=70'

# Skills related to the challenge: ['SQL injection','Web','Linux']
skills: ['Reverse Engineering']

# Recommended readings
recommendations:
    https://en.wikipedia.org/wiki/Debugger: 'Debugger'

# The emails of the Intellectual Property (IP) owners. Note that it is also possible that the owner is the same as the content creator.
owners: ['neorus666@gmail.com']
