# Version of the config.yml
version: "v2.0.0"

# Name of the challenge
name: "Dragon integer"

#Difficulty: 10 - 500
difficulty: 15

#Enable inputbox to submit flag: true | false
enable_flag_input: true

# If the solution is a fix string (static flag) you can add it here
flag: '{Y0u_$ucc3sfu11y_D3f3@t3d_7h3_Dr@g0n}'

# Skills related to the challenge: ['SQL injection','Web','Linux']
skills: ['Integer Overflow']

# Recommended readings
recommendations:
    https://en.wikipedia.org/wiki/Integer_overflow: 'Integer overflow (Wikipedia)'

# The emails of the Intellectual Property (IP) owners. Note that it is also possible that the owner is the same as the content creator.
owners: ['neorus666@gmail.com']

# CRP Config
crp_config:
    controller:
        ports: ['5555/controller']
    solvable:
        # Required Linux capabilities (See http://man7.org/linux/man-pages/man7/capabilities.7.html for the full list).
        # For example ["SETGID","SETUID"]
        # capabilities: [] # Not needed if empty
        ports: ['8888/tcp']
