# Version of the config.yml
version: "v2.0.0"

# Name of the challenge
name: 'Time to Attack'

# Challenge difficulty: 10 - 500
difficulty: 25

# Enable inputbox to submit flag: true | false
enable_flag_input: true

# If the solution is a fix string (static flag) you can add it here
flag: '3007199216121993'

# Skills related to the challenge: ['SQL injection','Web','Linux']
skills: ['Timing attack', 'Secure Coding']

# Recommended readings
recommendations:
    https://en.wikipedia.org/wiki/Side-channel_attack: 'Side-channel attack'
    https://en.wikipedia.org/wiki/Timing_attack: 'Timing attack'

# The emails of the Intellectual Property (IP) owners. Note that it is also possible that the owner is the same as the content creator.
owners: ['neorus666@gmail.com']
